### ISSUE TITLE
Fix --base_tables cmdline option.

### ISSUE THREAD

**Issue by mpope9** [mpope9/nba-sql#17]
If this is set to 'False' an error is generated due to a new player not being loaded. Player is no longer really a 'base table' as it relies on season. Might be worth moving this to pre-game table loading.

**Comment by avadhanij** [comment]
Since I am working on the option to _skip_ tables, I wanted to discuss this one as well.

Couple of issues
1. Stylistically, two word options are supposed to be separated by a `-`, not `_`. So it should be `--base-tables`.
2. As a flag, user should not be expected to pass `True` or `False`. Their presence alone should indicate true or false. This is done using `action=store_true` or `action=store_false`. 

In this case, since the default behavior is to always _load_ the base_tables, the flag should be for _skipping_ them. 

I propose changing this option to - `--skip-base-tables`. 

What do you think?

**Comment by mpope9** [comment]
These all make sense to me. Style makes more sense, the Boolean is redundant, agreed

**Comment by avadhanij** [comment]
Just wanted to check on this again - 

> Player is no longer really a 'base table' as it relies on season.

Doesn't seem that way. From both the ER diagram, and what I am seeing locally, player seems to be entirely independent. Did you mean `player_season`?

**Comment by mpope9** [comment]
Yes, I must have. This has been added, so I'll close this one as well.
